In [114]:
# Importing the Libraries

import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules
from mlxtend.preprocessing import TransactionEncoder
#from apyori import apriori
import seaborn as sns
import matplotlib.pyplot as plt
import networkx as nx

In [88]:
# Importing warnings

import warnings
warnings. filterwarnings('ignore')

In [62]:
# Loading the data

df = pd.read_csv(r"C:\Users\Shashi\Model Building\Unsupervised Learning or Descriptive Model\Association Rules\transactions_retail.csv")

In [63]:
# Checking the head of data

df.head()

   'HANGING'     'HEART' 'HOLDER'  'T-LIGHT'   'WHITE'       NA
0  'LANTERN'     'METAL'  'WHITE'        NaN       NaN      NaN
1     'COAT'     'CREAM'  'CUPID'   'HANGER'  'HEARTS'      NaN
2   'BOTTLE'      'FLAG'    'HOT'  'KNITTED'   'UNION'  'WATER'
3   'HEART.'    'HOTTIE'    'RED'    'WHITE'  'WOOLLY'      NaN
4        '7'  'BABUSHKA'  'BOXES'  'NESTING'     'SET'      NaN

In [64]:
# Droping NA Column 

df.pop('NA')

0             NaN
1             NaN
2         'WATER'
3             NaN
4             NaN
           ...
557035        NaN
557036        NaN
557037        NaN
557038        NaN
557039        NaN
Name: NA, Length: 557040, dtype: object

In [65]:
df.iloc[1]

'HANGING'      'COAT'
'HEART'       'CREAM'
'HOLDER'      'CUPID'
'T-LIGHT'    'HANGER'
'WHITE'      'HEARTS'
Name: 1, dtype: object

In [66]:
# 1. Gather All Items of Each Transactions into Numpy Array
transaction = []
for i in range(0,df.shape[0]):
    for j in range(0,df.shape[1]):
        transaction.append(df.values[i,j])

In [67]:
transaction = np.array(transaction)

In [68]:
transaction

array(["'LANTERN'", "'METAL'", "'WHITE'", ..., "'PIECE'", "'RETROSPOT'",
       "'SET'"], dtype='<U32')

In [69]:
#transform into dataframe
df_transaction = pd.DataFrame(transaction,columns=["Items"])

In [70]:
df_transaction

               Items
0          'LANTERN'
1            'METAL'
2            'WHITE'
3                nan
4                nan
...              ...
2785195          '9'
2785196     'BAKING'
2785197      'PIECE'
2785198  'RETROSPOT'
2785199        'SET'

[2785200 rows x 1 columns]

In [71]:
df_transaction['incident_count'] = 1 # Put 1 to Each Item For Making Countable Table, to be able to perform Group By

In [72]:
indexNames = df_transaction[df_transaction['Items'] == "nan" ].index

In [73]:
df_transaction.drop(indexNames,inplace=True)

In [74]:
# Final Step: Make a New Appropriate Pandas DataFrame for Visualizations  
df_table = df_transaction.groupby('Items').sum().sort_values('incident_count',ascending=False).reset_index()

In [75]:
df_table

            Items  incident_count
0           'BAG'           51911
1            'OF'           51177
2           'RED'           42069
3         'HEART'           38713
4           'SET'           38236
...           ...             ...
2569      'PANEL'               1
2570  'PARTITION'               1
2571    'POM-POM'               1
2572   'POSSIBLE'               1
2573       'zero'               1

[2574 rows x 2 columns]

In [76]:
# Initial Visualizations
df_table.head(10).style.background_gradient(cmap='Greens')

In [77]:
df_table['all']='all' #to have same origin

In [78]:
df_table

            Items  incident_count  all
0           'BAG'           51911  all
1            'OF'           51177  all
2           'RED'           42069  all
3         'HEART'           38713  all
4           'SET'           38236  all
...           ...             ...  ...
2569      'PANEL'               1  all
2570  'PARTITION'               1  all
2571    'POM-POM'               1  all
2572   'POSSIBLE'               1  all
2573       'zero'               1  all

[2574 rows x 3 columns]

In [91]:
# Transform Every Transaction to Seperate List & Gather Them into Numpy Array
transaction4 = []
for i in range(df.shape[0]):
    transaction4.append([str(df.values[i,j]) for j in range(df.shape[1])])

In [92]:
transaction4 = np.array(transaction4)

In [93]:
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()

In [94]:
tr_array = te.fit(transaction4).transform(transaction4)

In [95]:
te.columns_

["'!'",
 "'&'",
 "'''N'''",
 "'(22467)'",
 "'(22719)'",
 "'*Boombox'",
 "'*USB'",
 "'+'",
 "','",
 "',MAGIC'",
 "',PUDDINGS'",
 "'-'",
 "'-PAPER'",
 "'/'",
 "'0'",
 "'1'",
 "'1.8M'",
 "'10'",
 "'10/11/2010'",
 "'11'",
 "'12'",
 "'120CM'",
 "'125g'",
 "'15'",
 "'15C'",
 "'15CM'",
 "'16'",
 "'16954'",
 "'16955'",
 "'16956'",
 "'16957'",
 "'16960'",
 "'16961'",
 "'16963'",
 "'16965'",
 "'16X16CM'",
 "'17058'",
 "'17059'",
 "'17065'",
 "'17067'",
 "'17068'",
 "'17070'",
 "'17071'",
 "'17074'",
 "'17076'",
 "'17077'",
 "'17080'",
 "'17081'",
 "'17084'",
 "'17086'",
 "'17087'",
 "'17089'",
 "'17090'",
 "'17093'",
 "'17095'",
 "'17096'",
 "'17097'",
 "'17099'",
 "'17100'",
 "'17104'",
 "'17107'",
 "'17112'",
 "'17116'",
 "'17211'",
 "'17214'",
 "'17216'",
 "'17217'",
 "'17218'",
 "'17219'",
 "'17220'",
 "'17259'",
 "'17262'",
 "'1800'",
 "'18PC'",
 "'2'",
 "'20'",
 "'200'",
 "'20713'",
 "'20LIGHT'",
 "'21'",
 "'21/5/10'",
 "'22467'",
 "'22804'",
 "'23'",
 "'23343'",
 "'24'",
 "'250g'",
 "'25W,'",
 "'25x24x12cm'",
 "'3'",
 "'3.5g'",
 "'30'",
 "'30CM'",
 "'30CMx30CM'",
 "'34X20CM'",
 "'35'",
 "'36'",
 "'3D'",
 "'4'",
 "'40'",
 "'40CM'",
 "'40x40cm'",
 "'42'",
 "'42NECKL.'",
 "'45CM'",
 "'45x30cm'",
 "'45x45cm'",
 "'47'",
 "'5'",
 "'50'",
 "'50''S'",
 "'500g'",
 "'50CM'",
 "'6'",
 "'6''s'",
 "'60'",
 "'60CM'",
 "'60x40cm'",
 "'65CMx65CM'",
 "'6PC'",
 "'7'",
 "'70''S'",
 "'72'",
 "'75'",
 "'78'",
 "'8'",
 "'84930'",
 "'85123a'",
 "'9'",
 "'?'",
 "'?10.00'",
 "'?100.00'",
 "'?20.00'",
 "'?30.00'",
 "'?40.00'",
 "'?50.00'",
 "'??'",
 "'???'",
 "'????damages????'",
 "'????missing'",
 "'???lost'",
 "'???missing'",
 "'?display?'",
 "'?lost'",
 "'?missing'",
 "'?sold'",
 "'A'",
 "'A,B,C'",
 "'A4'",
 "'A5'",
 "'A6'",
 "'A7'",
 "'ABC'",
 "'ABSTRACT'",
 "'ACAPULCO'",
 "'ACCOUNT'",
 "'ACRYLIC'",
 "'ADDRESS'",
 "'ADE'",
 "'ADULT'",
 "'ADVENT'",
 "'AFGHAN'",
 "'AGED'",
 "'AHOY'",
 "'AID'",
 "'AIR'",
 "'AIRLINE'",
 "'AIRMAIL'",
 "'ALARM'",
 "'ALBUM'",
 "'ALL'",
 "'ALLIUM'",
 "'ALPHABET'",
 "'ALPINE'",
 "'ALUMINIUM'",
 "'AM'",
 "'AMAZON'",
 "'AMBER'",
 "'AMELIE'",
 "'AMETHYST'",
 "'AND'",
 "'ANEMONE'",
 "'ANGEL'",
 "'ANGEL,PINK'",
 "'ANGELS'",
 "'ANIMAL'",
 "'ANIMALS'",
 "'ANT'",
 "'ANTIQUE'",
 "'ANTOIENETT'",
 "'ANTOINETTE'",
 "'APERITIF'",
 "'APOTHECARY'",
 "'APPLE'",
 "'APPLES'",
 "'APRON'",
 "'AQUA'",
 "'AREA'",
 "'ARMY'",
 "'ART'",
 "'ART,ONLY'",
 "'ARTICULATED'",
 "'ARTIFICIAL'",
 "'ARTIIFCIAL'",
 "'ASHTRAY'",
 "'ASHTRAY,REVOLUTIONARY'",
 "'ASOS.'",
 "'ASS'",
 "'ASSORTED'",
 "'ASST'",
 "'ASSTD'",
 "'Adjust'",
 "'Adjustment'",
 "'Amazon'",
 "'Arouzer'",
 "'B'",
 "'B''DRAW'",
 "'B''FLY'",
 "'BABUSHKA'",
 "'BABY'",
 "'BACK'",
 "'BACKPACK'",
 "'BAD'",
 "'BADGES'",
 "'BAG'",
 "'BAGS'",
 "'BAIN'",
 "'BAKE'",
 "'BAKELIKE'",
 "'BAKER'",
 "'BAKING'",
 "'BALL'",
 "'BALLOON'",
 "'BALLOONS'",
 "'BALLS'",
 "'BALM'",
 "'BAMBOO'",
 "'BAND'",
 "'BANGLE'",
 "'BANK'",
 "'BANNER'",
 "'BANQUET'",
 "'BAR'",
 "'BARN'",
 "'BAROQUE'",
 "'BAROQUECANDLESTICK'",
 "'BARREL'",
 "'BARRIER'",
 "'BASE'",
 "'BASEBALL'",
 "'BASIL'",
 "'BASIN'",
 "'BASKET'",
 "'BASKETS'",
 "'BATH'",
 "'BATHROOM'",
 "'BATHS'",
 "'BATTERY'",
 "'BAUBLE'",
 "'BAUBLES'",
 "'BAZAAR'",
 "'BEA'",
 "'BEACH'",
 "'BEAD'",
 "'BEADED'",
 "'BEADS'",
 "'BEADS+HAND'",
 "'BEAK'",
 "'BEAKER'",
 "'BEAKERS'",
 "'BEAR'",
 "'BEATEN'",
 "'BEAUTIFUL'",
 "'BEAUTY'",
 "'BED'",
 "'BEDROOM'",
 "'BEDSIDE'",
 "'BEE'",
 "'BEETLES'",
 "'BELL'",
 "'BELLE'",
 "'BELLS'",
 "'BENDY'",
 "'BERRIES'",
 "'BERTIE'",
 "'BEST'",
 "'BEURRE'",
 "'BEWARE'",
 "'BIB'",
 "'BICYCLE'",
 "'BIG'",
 "'BILI'",
 "'BILL'",
 "'BILLBOARD'",
 "'BIN'",
 "'BIN,'",
 "'BINGO'",
 "'BIRD'",
 "'BIRDCAGE'",
 "'BIRDHOUSE'",
 "'BIRDIE'",
 "'BIRDS'",
 "'BIRDY'",
 "'BIRTHDAY'",
 "'BISCUIT'",
 "'BISCUITS'",
 "'BITTY'",
 "'BLACK'",
 "'BLACK+SILVER'",
 "'BLACK+WHITE'",
 "'BLACK/BLUE'",
 "'BLACK/WHITE'",
 "'BLACKBLUE'",
 "'BLACKBOARD'",
 "'BLACKCHRISTMAS'",
 "'BLANK'",
 "'BLING'",
 "'BLK/WHIT'",
 "'BLOCK'",
 "'BLOCKS'",
 "'BLOND'",
 "'BLOOD'",
 "'BLOSSOM'",
 "'BLUE'",
 "'BLUE/CREAM'",
 "'BLUE/GREEN'",
 "'BLUE/NAT'",
 "'BLUE/YELLOW'",
 "'BLUEBERRY'",
 "'BLUES'",
 "'BOARD'",
 "'BOBBLES'",
 "'BOHEMIAN'",
 "'BOMB'",
 "'BON'",
 "'BONBON'",
 "'BONBONS'",
 "'BONE'",
 "'BONHEUR'",
 "'BONNE'",
 "'BOOK'",
 "'BOOKCOVER'",
 "'BOOKS'",
 "'BOOM'",
 "'BOOT'",
 "'BOOZE'",
 "'BOTANICAL'",
 "'BOTANIQUE'",
 "'BOTTLE'",
 "'BOTTLES'",
 "'BOUDICCA'",
 "'BOUDOIR'",
 "'BOUQUET'",
 "'BOW'",
 "'BOWL'",
 "'BOWLS'",
 "'BOWS'",
 "'BOX'",
 "'BOX,FUNKY'",
 "'BOX.'",
 "'BOX/12'",
 "'BOXED'",
 "'BOXES'",
 "'BOY'",
 "'BOYS'",
 "'BRACELET'",
 "'BRACLET'",
 "'BRANCH'",
 "'BRASS'",
 "'BREAD'",
 "'BREAKFAST'",
 "'BRIAR'",
 "'BRIDGE'",
 "'BRIGHT'",
 "'BROCADE'",
 "'BROCANTE'",
 "'BRONZE'",
 "'BROOCH'",
 "'BROWN'",
 "'BRUSH'",
 "'BUBBLE'",
 "'BUBBLEGUM'",
 "'BUBBLES'",
 "'BUCKET'",
 "'BUDAH'",
 "'BUDDHA'",
 "'BUFFALO'",
 "'BUILDING'",
 "'BULB'",
 "'BULL'",
 "'BULLET'",
 "'BUM'",
 "'BUNDLE'",
 "'BUNNIES'",
 "'BUNNY'",
 "'BUNTING'",
 "'BURGUNDY'",
 "'BURNER'",
 "'BURST'",
 "'BUS'",
 "'BUSY'",
 "'BUTTER'",
 "'BUTTERFILES'",
 "'BUTTERFL'",
 "'BUTTERFLIES'",
 "'BUTTERFLIES,PINK'",
 "'BUTTERFLY'",
 "'BUTTERFLY/CRYSTAL'",
 "'BUTTON'",
 "'BUTTONS'",
 "'Ball'",
 "'Bank'",
 "'Breakages'",
 "'C'",
 "'C/COVER'",
 "'C550456'",
 "'CABIN'",
 "'CABINET'",
 "'CABINET,'",
 "'CACTI'",
 "'CACTUS'",
 "'CADDY'",
 "'CADET'",
 "'CAFE'",
 "'CAGE'",
 "'CAKE'",
 "'CAKES'",
 "'CAKESTAND'",
 "'CAKESTAND,'",
 "'CALCULATOR'",
 "'CALENDAR'",
 "'CALM'",
 "'CAMDEN'",
 "'CAMEMBERT'",
 "'CAMO'",
 "'CAMOUFLAGE'",
 "'CAMPAGNE'",
 "'CAMPER'",
 "'CAMPHOR'",
 "'CAMPING'",
 "'CAN'",
 "'CAN''T'",
 "'CANARY'",
 "'CANDELABRA'",
 "'CANDLE'",
 "'CANDLE+INCENSE'",
 "'CANDLEHOLDER'",
 "'CANDLEPOT'",
 "'CANDLES'",
 "'CANDLESTAND'",
 "'CANDLESTICK'",
 "'CANDY'",
 "'CANDYSTUFT'",
 "'CANNABIS'",
 "'CANNISTER'",
 "'CANVAS'",
 "'CAP'",
 "'CAPIZ'",
 "'CAR'",
 "'CARAVAN'",
 "'CARD'",
 "'CARD,'",
 "'CARD,SQUARE,'",
 "'CARD,pack/12'",
 "'CARDHOLDER'",
 "'CARDS'",
 "'CARLO'",
 "'CARNIVAL'",
 "'CAROUSEL'",
 "'CARPET'",
 "'CARRIAGE'",
 "'CARRIER'",
 "'CARROT'",
 "'CARRY'",
 "'CARRY-ALL'",
 "'CARS'",
 "'CARTOON'",
 "'CASE'",
 "'CASES'",
 "'CASH+CARRY'",
 "'CAST'",
 "'CAT'",
 "'CATCH'",
 "'CATS'",
 "'CD'",
 "'CEATURE'",
 "'CELEBRATION'",
 "'CENTURY'",
 "'CERAMIC'",
 "'CHAIN'",
 "'CHAIN,THE'",
 "'CHAIR'",
 "'CHALET'",
 "'CHALICE'",
 "'CHALK'",
 "'CHALKBOARD'",
 "'CHAMBRE'",
 "'CHAMPAGNE'",
 "'CHAMPION'",
 "'CHANDELIER'",
 "'CHANDLER'",
 "'CHAR'",
 "'CHARGE'",
 "'CHARGER'",
 "'CHARLIE'",
 "'CHARLIE+LOLA'",
 "'CHARLIE+LOLAEXTREMELY'",
 "'CHARLOTTE'",
 "'CHARM'",
 "'CHARMS'",
 "'CHART'",
 "'CHASING'",
 "'CHATEAU'",
 "'CHECK'",
 "'CHEERFUL'",
 "'CHEESE'",
 "'CHENILLE'",
 "'CHERRY'",
 "'CHERUB'",
 "'CHEST'",
 "'CHESTS'",
 "'CHIC'",
 "'CHICK'",
 "'CHICKEN'",
 "'CHICKEN,'",
 "'CHICKS'",
 "'CHILDHOOD'",
 "'CHILDREN'",
 "'CHILDREN''S'",
 "'CHILDRENS'",
 "'CHILDS'",
 "'CHILLI'",
 "'CHIME'",
 "'CHINA'",
 "'CHINESE'",
 "'CHIVES'",
 "'CHOC'",
 "'CHOC+BLUE'",
 "'CHOCOLATE'",
 "'CHOCOLATECANDLE'",
 "'CHOCOLATES'",
 "'CHOICE'",
 "'CHOIR'",
 "'CHOKER'",
 "'CHOPPING'",
 "'CHOPSTICKS'",
 "'CHRISTMAS'",
 "'CHROME'",
 "'CHRYSANTHEMUM'",
 "'CHRYSANTHEMUMS'",
 "'CHUNKY'",
 "'CIGAR'",
 "'CINAMMON'",
 "'CINDERELLA'",
 "'CINNAMON'",
 "'CIRCLE'",
 "'CIRCLES'",
 "'CIRCULAR'",
 "'CIRCUS'",
 "'CITRONELLA'",
 "'CITRUS'",
 "'CLAIRE'",
 "'CLAM'",
 "'CLASS'",
 "'CLASSIC'",
 "'CLASSICAL'",
 "'CLAY'",
 "'CLEAN'",
 "'CLEAR'",
 "'CLIMBING'",
 "'CLIP'",
 "'CLIPS'",
 "'CLOCHE'",
 "'CLOCK'",
 "'CLOSED'",
 "'CLOTH'",
 "'CLOTHES'",
 "'CLUSTER'",
 "'COASTER'",
 "'COASTER,ELVIS'",
 "'COASTERS'",
 "'COAT'",
 "'COATHANGER'",
 "'COCKEREL'",
 "'COCKLE'",
 "'COCKTAIL'",
 "'COCONUT'",
 "'COFFEE'",
 "'COL'",
 "'COLANDER'",
 "'COLLAGE'",
 "'COLLAR'",
 "'COLOUR'",
 "'COLOURED'",
 "'COLOURFUL'",
 "'COLOURING'",
 "'COLOURS'",
 "'COLUMBIAN'",
 "'COMB'",
 "'COMBO'",
 "'COME'",
 "'COMPACT'",
 "'CONDIMENT'",
 "'CONE'",
 "'CONES'",
 "'CONEY'",
 "'CONFECTIONERY'",
 "'CONFETTI'",
 "'CONFUSING'",
 "'CONGRATULATIONS'",
 "'CONTAINER'",
 "'COOK'",
 "'COOKIE'",
 "'COOKING'",
 "'COPPER'",
 "'COPPER/OLIVE'",
 "'CORDIAL'",
 "'CORDON'",
 "'CORER'",
 "'CORNICE'",
 "'CORONA'",
 "'COSMETIC'",
 "'COSMETICS'",
 "'COSY'",
 "'COTE'",
 "'COTTAGE'",
 "'COTTON'",
 "'COUNTRY'",
 "'COVENT'",
 "'COVER'",
 "'COWBOY'",
 "'COWBOYS'",
 "'CRACKED'",
 "'CRACKER'",
 "'CRACKERS'",
 "'CRACKLE'",
 "'CRAFT'",
 "'CRATE'",
 "'CRATES'",
 "'CRAWLIE'",
 "'CRAWLIES'",
 "'CRAYONS'",
 "'CRAZY'",
 "'CREAM'",
 "'CREATURES'",
 "'CREDIT'",
 "'CREEPY'",
 "'CRESTED'",
 "'CROCHET'",
 "'CROME'",
 "'CROQUET'",
 "'CROSS'",
 "'CROSSBONES'",
 "'CROSSES'",
 "'CROWNS'",
 "'CRUK'",
 "'CRUSOE'",
 "'CRYSTAL'",
 "'CRYSTAL+GLASS'",
 "'CRYSTALS'",
 "'CUBE'",
 "'CUBES'",
 "'CUBIC'",
 "'CUP'",
 "'CUPBOARD'",
 "'CUPCAKE'",
 "'CUPCAKES'",
 "'CUPID'",
 "'CUPS'",
 "'CURIO'",
 "'CURIOUS'",
 "'CURTAIN'",
 "'CUSHION'",
 "'CUSHIONS'",
 "'CUT'",
 "'CUTE'",
 "'CUTGLASS'",
 "'CUTLERY'",
 "'CUTTER'",
 "'CUTTERS'",
 "'CZECH'",
 "'Cab'",
 "'Carriage'",
 "'Charges'",
 "'Classic'",
 "'Commission'",
 "'Crushed'",
 "'D'",
 "'D''AZURE'",
 "'D.O.F.'",
 "'DAD'",
 "'DADS'",
 "'DAIRY'",
 "'DAISIES'",
 "'DAISY'",
 "'DAMAGED'",
 "'DAMAGES'",
 "'DANISH'",
 "'DARK'",
 "'DAVID''S'",
 "'DAY'",
 "'DAYS'",
 "'DE'",
 "'DEC'",
 "'DECK'",
 "'DECO'",
 "'DECO.WHITE'",
 "'DECORATION'",
 "'DECORATIONS'",
 "'DECORATIVE'",
 "'DECOUPAGE'",
 "'DECOUPAGE,GREETING'",
 "'DECROTIVEVINTAGE'",
 "'DELIGHT'",
 "'DELPHINIUM'",
 "'DELUXE'",
 "'DEMI'",
 "'DENIM'",
 "'DES'",
 "'DESIGN'",
 "'DESIGNS'",
 "'DESK'",
 "'DIA'",
 "'DIAMANTE'",
 "'DIAMON'",
 "'DIAMOND'",
 "'DIET'",
 "'DIGESTIVE'",
 "'DIGITALIS'",
 "'DINER'",
 "'DINKY'",
 "'DINNER'",
 "'DINOSAUR'",
 "'DINOSAURS'",
 "'DISC'",
 "'DISC/MIRROR'",
 "'DISCO'",
 "'DISH'",
 "'DISPENSER'",
 "'DISPLAY'",
 "'DISPOSABLE'",
 "'DIVA'",
 "'DO'",
 "'DOC'",
 "'DOCTOR''S'",
 "'DOG'",
 "'DOGGY'",
 "'DOGS'",
 "'DOILEY'",
 "'DOILIES'",
 "'DOILY'",
 "'DOLL'",
 "'DOLLCRAFT'",
 "'DOLLY'",
 "'DOLPHIN'",
 "'DOLPHINS'",
 "'DOMINOES'",
 "'DONKEY'",
 "'DOOR'",
 "'DOORBELL'",
 "'DOORKNOB'",
 "'DOORMAT'",
 "'DOORS'",
 "'DOORSIGN'",
 "'DOORSTOP'",
 "'DOT'",
 "'DOTCOM'",
 "'DOTCOMGIFTSHOP'",
 "'DOTCOMGIFTSHOP.COM'",
 "'DOTS'",
 "'DOUBLE'",
 "'DOUGHNUT'",
 "'DOUGHNUTS'",
 "'DOVE'",
 "'DOVECOTE'",
 "'DOWN'",
 "'DRAGON'",
 "'DRAGONFLY'",
 "'DRAGONS'",
 "'DRAW'",
 "'DRAWER'",
 "'DRAWERKNOB'",
 "'DRAWERS'",
 "'DRAWING'",
 "'DRAWSTRING'",
 "'DREAM'",
 "'DREAMS'",
 "'DRESS'",
 "'DRESSING'",
 "'DRINK'",
 "'DROP'",
 "'DROPLET'",
 "'DU'",
 "'DUCK'",
 "'DUCKS'",
 "'DUSTY'",
 "'DUTCH'",
 "'Dad''s'",
 "'Dagamed'",
 "'Damaged'",
 "'Damages'",
 "'Damages/samples'",
 "'Day'",
 "'Discount'",
 "'Display'",
 "'Dotcom'",
 "'Dotcomgiftshop'",
 "'Dr.'",
 "'E'",
 "'EAR'",
 "'EARRING'",
 "'EARRINGS'",
 "'EARTH'",
 "'EASTER'",
 "'EAU'",
 "'ECONOMY'",
 "'EDGE)'",
 "'EDWARDIAN'",
 "'EGG'",
 "'EGGS'",
 "'EIGHT'",
 "'ELEGANT'",
 "'ELEPHANT'",
 "'ELEPHANT,'",
 "'ELIXIR'",
 "'ELVIS'",
 "'EMBOSSED'",
 "'EMBROIDERED'",
 "'EMBROIDERY'",
 "'EMERGENCY'",
 "'EMILY'",
 "'EMPIRE'",
 "'EN'",
 "'ENAMEL'",
 "'ENAMEL+GLASS'",
 "'ENCHANTED'",
 "'ENFANTS'",
 "'ENGINE/CAR'",
 "'ENGLAND'",
 "'ENGLISH'",
 "'ENGRAVED'",
 "'ENVELOPE'",
 "'ENVELOPES'",
 "'ERASER'",
 "'ERASERS'",
 "'ERROR,'",
 "'ESSENTIAL'",
 "'ETCHED'",
 "'EUCALYPTUS'",
 "'EVENING'",
 "'EXERCISE'",
 "'EXPANDABLE'",
 "'EYE'",
 "'Electronic'",
 "'F'",
 "'FABRIC'",
 "'FACE'",
 "'FACETED'",
 "'FAIR'",
 "'FAIRY'",
 "'FAIRY,5'",
 "'FAMILY'",
 "'FAN'",
 "'FANCY'",
 "'FANNY''S'",
 "'FARM'",
 "'FARMYARD'",
 "'FARTHING'",
 "'FASHION'",
 "'FAUNA'",
 "'FAUX'",
 "'FAVOURITES'",
 "'FAWN'",
 "'FBA'",
 "'FEATHER'",
 "'FEATHERS'",
 "'FEE'",
 "'FEEDER'",
 "'FEEDING'",
 "'FELT'",
 "'FELTCRAFT'",
 "'FENG'",
 "'FERN'",
 "'FIELD'",
 "'FIELDS'",
 "'FIGURES'",
 "'FILIGREE'",
 "'FILIGRIS'",
 "'FILLER'",
 "'FINE'",
 "'FINGER'",
 "'FINISH'",
 "'FIRE'",
 "'FIRST'",
 "'FISHING'",
 "'FIVE'",
 "'FLAG'",
 "'FLAGS'",
 "'FLAME'",
 "'FLAMES'",
 "'FLAMINGO'",
 "'FLANNEL'",
 "'FLASK'",
 "'FLOCK'",
 "'FLOOR'",
 "'FLORA'",
 "'FLORAL'",
 "'FLORE'",
 "'FLOWE'",
 "'FLOWER'",
 "'FLOWER/BUTTERFLY'",
 "'FLOWERPOT'",
 "'FLOWERPOWER'",
 "'FLOWERS'",
 "'FLOWR'",
 "'FLU'",
 "'FLUFFY'",
 "'FLUTED'",
 "'FLY'",
 "'FLYING'",
 "'FLYTRAP'",
 "'FOB'",
 "'FOIL'",
 "'FOLDING'",
 "'FOLK'",
 "'FOLKART'",
 "'FONDANT'",
 "'FONT'",
 "'FONTS'",
 "'FOOD'",
 "'FOOD/DRINK'",
 "'FOOT'",
 "'FOOTBALL'",
 "'FOOTPRINTS'",
 "'FOR'",
 "'FOREST'",
 "'FORK'",
 "'FORKED'",
 "'FORTIES'",
 "'FOUND'",
 "'FOUR'",
 "'FOXGLOVE'",
 "'FOXY'",
 "'FRAGRANCE'",
 "'FRAME'",
 "'FRAMES'",
 "'FRANCE'",
 "'FRANGIPANI'",
 "'FRAPPUCINO'",
 "'FREESTYLE'",
 "'FRENCH'",
 "'FRESH'",
 "'FRESHWATER'",
 "'FRIDGE'",
 "'FRIENDS'",
 "'FRIENDSHIP'",
 "'FRIEZE'",
 "'FRILL'",
 "'FRINGE'",
 "'FROG'",
 "'FROM'",
 "'FRONT'",
 "'FROST'",
 "'FROSTED'",
 "'FRUIT'",
 "'FRUIT+FLOWERS'",
 "'FRUITBOWL'",
 "'FRUITS'",
 "'FRUTTI'",
 "'FRYING'",
 "'FULL'",
 "'FUN'",
 "'FUNKY'",
 "'FUNNY'",
 "'FUR'",
 "'FUSCHIA'",
 "'Found'",
 "'G'",
 "'GAME'",
 "'GAMES'",
 "'GAOLERS'",
 "'GARAGE'",
 "'GARDEN'",
 "'GARDENERS'",
 "'GARDENIA'",
 "'GARDENS'",
 "'GARLAND'",
 "'GARLAND,'",
 "'GARLD'",
 "'GAUZE'",
 "'GAZEBO'",
 "'GEBRA'",
 "'GECKO'",
 "'GEISHA'",
 "'GEL'",
 "'GEMS'",
 "'GEMSTONE'",
 "'GENTLEMAN'",
 "'GENTLEMEN'",
 "'GENTS'",
 ...]

In [96]:
tr_array

array([[False, False, False, ..., False, False,  True],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False,  True],
       [False, False, False, ..., False, False,  True],
       [False, False, False, ..., False, False, False]])

In [97]:
dataset = pd.DataFrame(tr_array,columns=te.columns_)

In [98]:
dataset.shape

(557040, 2575)

In [99]:
first25 = df_table["Items"].head(25).values # Select Top25
dataset = dataset.loc[:,first25] # Extract Top25
dataset

,'BAG','OF','RED','HEART','SET','RETROSPOT','DESIGN','VINTAGE','PINK','CHRISTMAS',...,'3','LUNCH','WHITE','HANGING','HOLDER','SIGN','T-LIGHT','PACK','PAPER','SMALL'
0,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,True,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557035,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
557036,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
557037,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
557038,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
557039,False,False,False,False,True,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [100]:
dataset.columns

Index([''BAG'', ''OF'', ''RED'', ''HEART'', ''SET'', ''RETROSPOT'', ''DESIGN'',
       ''VINTAGE'', ''PINK'', ''CHRISTMAS'', ''BOX'', ''CAKE'', ''JUMBO'',
       ''METAL'', ''BLUE'', ''3'', ''LUNCH'', ''WHITE'', ''HANGING'',
       ''HOLDER'', ''SIGN'', ''T-LIGHT'', ''PACK'', ''PAPER'', ''SMALL''],
      dtype='object')

In [101]:
# Convert dataset into 1-0 encoding

def encode_units(x):
    if x == False:
        return 0 
    if x == True:
        return 1

In [102]:
dataset = dataset.applymap(encode_units)
dataset.head(10)

,'BAG','OF','RED','HEART','SET','RETROSPOT','DESIGN','VINTAGE','PINK','CHRISTMAS',...,'3','LUNCH','WHITE','HANGING','HOLDER','SIGN','T-LIGHT','PACK','PAPER','SMALL'
0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [103]:
frequent_itemsets = apriori(dataset, min_support=0.01, use_colnames=True)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets

     support                          itemsets  length
0   0.093191                           ('BAG')       1
1   0.091873                            ('OF')       1
2   0.075522                           ('RED')       1
3   0.069498                         ('HEART')       1
4   0.068641                           ('SET')       1
5   0.060572                     ('RETROSPOT')       1
6   0.053975                        ('DESIGN')       1
7   0.053258                       ('VINTAGE')       1
8   0.051246                          ('PINK')       1
9   0.045115                     ('CHRISTMAS')       1
10  0.043808                           ('BOX')       1
11  0.038527                          ('CAKE')       1
12  0.037949                         ('JUMBO')       1
13  0.036507                         ('METAL')       1
14  0.034676                          ('BLUE')       1
15  0.033561                             ('3')       1
16  0.033256                         ('LUNCH')       1
17  0.032262                         ('WHITE')       1
18  0.030312                       ('HANGING')       1
19  0.029190                        ('HOLDER')       1
20  0.027070                          ('SIGN')       1
21  0.025842                       ('T-LIGHT')       1
22  0.025727                          ('PACK')       1
23  0.025359                         ('PAPER')       1
24  0.024382                         ('SMALL')       1
25  0.014891                    ('RED', 'BAG')       2
26  0.014961              ('BAG', 'RETROSPOT')       2
27  0.017112                 ('DESIGN', 'BAG')       2
28  0.012933                ('VINTAGE', 'BAG')       2
29  0.034055                  ('JUMBO', 'BAG')       2
30  0.024761                  ('LUNCH', 'BAG')       2
31  0.010258                   ('OF', 'HEART')       2
32  0.022440                     ('OF', 'SET')       2
33  0.015500                    ('OF', 'CAKE')       2
34  0.013888                       ('OF', '3')       2
35  0.023032                    ('OF', 'PACK')       2
36  0.036380              ('RED', 'RETROSPOT')       2
37  0.013627              ('HANGING', 'HEART')       2
38  0.012295               ('HOLDER', 'HEART')       2
39  0.010405              ('T-LIGHT', 'HEART')       2
40  0.010416               ('LUNCH', 'DESIGN')       2
41  0.023724                 ('METAL', 'SIGN')       2
42  0.011798             ('HOLDER', 'HANGING')       2
43  0.013572            ('T-LIGHT', 'HANGING')       2
44  0.019620             ('HOLDER', 'T-LIGHT')       2
45  0.012493       ('RED', 'BAG', 'RETROSPOT')       3
46  0.010416        ('LUNCH', 'DESIGN', 'BAG')       3
47  0.010405    ('HOLDER', 'HEART', 'T-LIGHT')       3
48  0.011480  ('HOLDER', 'HANGING', 'T-LIGHT')       3

In [104]:
frequent_itemsets[ (frequent_itemsets['length'] == 2) &
                   (frequent_itemsets['support'] >= 0.02) ]

     support              itemsets  length
29  0.034055      ('JUMBO', 'BAG')       2
30  0.024761      ('LUNCH', 'BAG')       2
32  0.022440         ('OF', 'SET')       2
35  0.023032        ('OF', 'PACK')       2
36  0.036380  ('RED', 'RETROSPOT')       2
41  0.023724     ('METAL', 'SIGN')       2

In [105]:
frequent_itemsets[ (frequent_itemsets['length'] == 3) ].head()

     support                          itemsets  length
45  0.012493       ('RED', 'BAG', 'RETROSPOT')       3
46  0.010416        ('LUNCH', 'DESIGN', 'BAG')       3
47  0.010405    ('HOLDER', 'HEART', 'T-LIGHT')       3
48  0.011480  ('HOLDER', 'HANGING', 'T-LIGHT')       3

In [106]:
# Import Association Rules Algo

rules = association_rules(frequent_itemsets,metric='lift',min_threshold=1.2)

In [107]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,('RED'),('BAG'),0.075522,0.093191,0.014891,0.197176,2.115832,0.007853,1.129524
1,('BAG'),('RED'),0.093191,0.075522,0.014891,0.159793,2.115832,0.007853,1.100297
2,('BAG'),('RETROSPOT'),0.093191,0.060572,0.014961,0.160544,2.650468,0.009316,1.119091
3,('RETROSPOT'),('BAG'),0.060572,0.093191,0.014961,0.246999,2.650468,0.009316,1.204261
4,('DESIGN'),('BAG'),0.053975,0.093191,0.017112,0.317036,3.402008,0.012082,1.327755
...,...,...,...,...,...,...,...,...,...
59,"('HOLDER', 'T-LIGHT')",('HANGING'),0.019620,0.030312,0.011480,0.585140,19.303917,0.010886,2.337389
60,"('T-LIGHT', 'HANGING')",('HOLDER'),0.013572,0.029190,0.011480,0.845899,28.979080,0.011084,6.299849
61,('HOLDER'),"('T-LIGHT', 'HANGING')",0.029190,0.013572,0.011480,0.393296,28.979080,0.011084,1.625882
62,('HANGING'),"('HOLDER', 'T-LIGHT')",0.030312,0.019620,0.011480,0.378739,19.303917,0.010886,1.578048
63,('T-LIGHT'),"('HOLDER', 'HANGING')",0.025842,0.011798,0.011480,0.444251,37.654571,0.011175,1.778146

In [108]:
rules['antecedents_len'] = rules['antecedents'].apply(lambda x: len(x))
rules['consequents_len'] = rules['consequents'].apply(lambda x: len(x))

In [109]:
rules.sort_values("lift",ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedents_len,consequents_len
63,('T-LIGHT'),"('HOLDER', 'HANGING')",0.025842,0.011798,0.011480,0.444251,37.654571,0.011175,1.778146,1,2
58,"('HOLDER', 'HANGING')",('T-LIGHT'),0.011798,0.025842,0.011480,0.973068,37.654571,0.011175,36.170433,2,1
55,('HOLDER'),"('T-LIGHT', 'HEART')",0.029190,0.010405,0.010405,0.356458,34.258303,0.010101,1.537731,1,2
54,"('T-LIGHT', 'HEART')",('HOLDER'),0.010405,0.029190,0.010405,1.000000,34.258303,0.010101,inf,2,1
57,('T-LIGHT'),"('HOLDER', 'HEART')",0.025842,0.012295,0.010405,0.402640,32.747332,0.010087,1.653449,1,2
...,...,...,...,...,...,...,...,...,...,...,...
6,('VINTAGE'),('BAG'),0.053258,0.093191,0.012933,0.242829,2.605716,0.007969,1.197628,1,1
1,('BAG'),('RED'),0.093191,0.075522,0.014891,0.159793,2.115832,0.007853,1.100297,1,1
0,('RED'),('BAG'),0.075522,0.093191,0.014891,0.197176,2.115832,0.007853,1.129524,1,1
13,('HEART'),('OF'),0.069498,0.091873,0.010258,0.147599,1.606553,0.003873,1.065375,1,1
12,('OF'),('HEART'),0.091873,0.069498,0.010258,0.111652,1.606553,0.003873,1.047452,1,1

In [110]:
rules.sort_values("confidence",ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedents_len,consequents_len
46,"('LUNCH', 'DESIGN')",('BAG'),0.010416,0.093191,0.010416,1.000000,10.730674,0.009445,inf,2,1
54,"('T-LIGHT', 'HEART')",('HOLDER'),0.010405,0.029190,0.010405,1.000000,34.258303,0.010101,inf,2,1
58,"('HOLDER', 'HANGING')",('T-LIGHT'),0.011798,0.025842,0.011480,0.973068,37.654571,0.011175,36.170433,2,1
8,('JUMBO'),('BAG'),0.037949,0.093191,0.034055,0.897393,9.629636,0.030519,8.837732,1,1
21,('PACK'),('OF'),0.025727,0.091873,0.023032,0.895262,9.744548,0.020669,8.670464,1,1
...,...,...,...,...,...,...,...,...,...,...,...
13,('HEART'),('OF'),0.069498,0.091873,0.010258,0.147599,1.606553,0.003873,1.065375,1,1
7,('BAG'),('VINTAGE'),0.093191,0.053258,0.012933,0.138776,2.605716,0.007969,1.099298,1,1
44,('BAG'),"('RED', 'RETROSPOT')",0.093191,0.036380,0.012493,0.134056,3.684913,0.009103,1.112798,1,2
51,('BAG'),"('LUNCH', 'DESIGN')",0.093191,0.010416,0.010416,0.111768,10.730674,0.009445,1.114106,1,2
12,('OF'),('HEART'),0.091873,0.069498,0.010258,0.111652,1.606553,0.003873,1.047452,1,1

In [111]:
rules[~rules['consequents'].str.contains('SET', regex=False) &
      ~rules['antecedents'].str.contains('SET', regex=False)].sort_values('confidence',ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedents_len,consequents_len
46,"('LUNCH', 'DESIGN')",('BAG'),0.010416,0.093191,0.010416,1.000000,10.730674,0.009445,inf,2,1
54,"('T-LIGHT', 'HEART')",('HOLDER'),0.010405,0.029190,0.010405,1.000000,34.258303,0.010101,inf,2,1
58,"('HOLDER', 'HANGING')",('T-LIGHT'),0.011798,0.025842,0.011480,0.973068,37.654571,0.011175,36.170433,2,1
8,('JUMBO'),('BAG'),0.037949,0.093191,0.034055,0.897393,9.629636,0.030519,8.837732,1,1
21,('PACK'),('OF'),0.025727,0.091873,0.023032,0.895262,9.744548,0.020669,8.670464,1,1
...,...,...,...,...,...,...,...,...,...,...,...
13,('HEART'),('OF'),0.069498,0.091873,0.010258,0.147599,1.606553,0.003873,1.065375,1,1
7,('BAG'),('VINTAGE'),0.093191,0.053258,0.012933,0.138776,2.605716,0.007969,1.099298,1,1
44,('BAG'),"('RED', 'RETROSPOT')",0.093191,0.036380,0.012493,0.134056,3.684913,0.009103,1.112798,1,2
51,('BAG'),"('LUNCH', 'DESIGN')",0.093191,0.010416,0.010416,0.111768,10.730674,0.009445,1.114106,1,2
12,('OF'),('HEART'),0.091873,0.069498,0.010258,0.111652,1.606553,0.003873,1.047452,1,1

In [112]:
confidence = rules[~rules['consequents'].str.contains('OF', regex=False) &
      ~rules['antecedents'].str.contains('OF', regex=False)].sort_values('confidence',ascending=False)

In [113]:
confidence[confidence['confidence']>=0.7]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedents_len,consequents_len
46,"('LUNCH', 'DESIGN')",('BAG'),0.010416,0.093191,0.010416,1.000000,10.730674,0.009445,inf,2,1
54,"('T-LIGHT', 'HEART')",('HOLDER'),0.010405,0.029190,0.010405,1.000000,34.258303,0.010101,inf,2,1
58,"('HOLDER', 'HANGING')",('T-LIGHT'),0.011798,0.025842,0.011480,0.973068,37.654571,0.011175,36.170433,2,1
8,('JUMBO'),('BAG'),0.037949,0.093191,0.034055,0.897393,9.629636,0.030519,8.837732,1,1
21,('PACK'),('OF'),0.025727,0.091873,0.023032,0.895262,9.744548,0.020669,8.670464,1,1
33,('SIGN'),('METAL'),0.027070,0.036507,0.023724,0.876384,24.005761,0.022735,7.794263,1,1
52,"('HOLDER', 'HEART')",('T-LIGHT'),0.012295,0.025842,0.010405,0.846255,32.747332,0.010087,6.336190,2,1
60,"('T-LIGHT', 'HANGING')",('HOLDER'),0.013572,0.029190,0.011480,0.845899,28.979080,0.011084,6.299849,2,1
40,"('RED', 'BAG')",('RETROSPOT'),0.014891,0.060572,0.012493,0.838939,13.850290,0.011591,5.832751,2,1
42,"('BAG', 'RETROSPOT')",('RED'),0.014961,0.075522,0.012493,0.835013,11.056497,0.011363,5.603343,2,1
39,('T-LIGHT'),('HOLDER'),0.025842,0.029190,0.019620,0.759222,26.009655,0.018865,4.031971,1,1
10,('LUNCH'),('BAG'),0.033256,0.093191,0.024761,0.744561,7.989645,0.021662,3.550009,1,1